import type { Metadata } from "next";
import { Geist, Geist_Mono, DynaPuff } from "next/font/google";
import "./globals.css";
import { auth } from "../auth";
import Header from "@/components/Header";
import Image from "next/image";
import { SessionProvider } from "next-auth/react"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dynapuff = DynaPuff({
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${dynapuff.className} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
        <Image 
                src="/HomeBee.png"
                alt="StudyComb Icon"
                width={60}
                height={60}
                className="homeBee"
                />
        <Header session={session}></Header>
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
